### PR TITLE
Fix something

### PR DESCRIPTION
**Pull request by nihsmik**

### CODE REVIEW

**Comment by nihsmik** [comment]
is_integer(nil) returns false

**Comment by Dalgona** [comment]
`nil` checks are necessary because the default value `200` should be used when `preview_length` is not set.

**Comment by nihsmik** [comment]
I changed the condition into `unless is_nil(p) || is_integer(p)`
I tested it from my local.
`preview_length` does not existed => No error.
`preview_length` is `200` => No error.
`preview_length` is `asdfasdf` => Error.

Thank you for your comment :)

**Comment by Dalgona** [comment]
Thank you for your PR. However validation codes have been rewritten using [ex_json_schema](https://github.com/jonasschmidt/ex_json_schema) in c0cbde9. I thought this is more flexible and future-proof method to validate JSON files.

**Pull request closed without merging**
